# This file is used for the continuous integration service at
# https://travis-ci.org/

language: python

# Pick python versions to use in testing.
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  # Install dependencies for wxPython Phoenix.
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libjpeg-dev libtiff-dev
  - sudo apt-get install -y libgtk2.0-dev
  - sudo apt-get install -y libsdl1.2-dev libgstreamer-plugins-base0.10-dev
  
  # Install nose so we can use nosetests to run our tests.
  - pip install nose

# Install ShellFash package and dependencies using pip.
install:
  # wxPython Phoenix must be installed specially because it
  # is not on PYPI as of this writing.
  # Grab a pre-compiled version for Ubuntu based on the Python version.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install --pre https://github.com/tyost/ShellFashDependencies/releases/download/wxPython_Phoenix-3.0.3.dev1820.49a8884/wxPython_Phoenix-3.0.3.dev1820.49a8884-cp32-cp32mu-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install --pre https://github.com/tyost/ShellFashDependencies/releases/download/wxPython_Phoenix-3.0.3.dev1820.49a8884/wxPython_Phoenix-3.0.3.dev1820.49a8884-cp33-cp33m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install --pre https://github.com/tyost/ShellFashDependencies/releases/download/wxPython_Phoenix-3.0.3.dev1820.49a8884/wxPython_Phoenix-3.0.3.dev1820.49a8884-cp34-cp34m-linux_x86_64.whl; fi
  
  # Install ShellFash.
  - pip install -e .

# Run the tests.
script:
  # TODO: Run a pep8 . check.

  # For debugging, list everything in the current directory.
  - ls
  
  # Find and run the tests using nose.
  - nosetests
